gateio:
  api_key: "82efe70ce1487c2ad0c477d45b55ac9e"
  api_secret: "36d5a8c0ac491483b1325f76bbf26f9913c7282c641d105256ce0f7c264a0b0a"

notifications:
  ntfy_topic: "Gate-io_Price_Monitoring_Bot-01"  # Create your own topic at ntfy.sh

monitoring:
  top_n: 25                      # Number of coins in each ranking
  change_alert_threshold: 10     # Alert when entering/exiting top X price changes
  range_alert_threshold: 10      # Alert when entering/exiting top X price ranges
  update_frequency_seconds: 300  # Update interval (5 minutes)
  max_iterations: 0              # 0 for infinite, any number for limited runs
  alert_cooldown_seconds: 600    # Cooldown period for alerts (10 minutes)
